/*
	Copyright 2023 secworks

	Author: Joachim Strombergson ()

	This file is auto-generated by wrapper_gen.py on 2023-11-28

	Permission is hereby granted, free of charge, to any person obtaining
	a copy of this software and associated documentation files (the
	"Software"), to deal in the Software without restriction, including
	without limitation the rights to use, copy, modify, merge, publish,
	distribute, sublicense, and/or sell copies of the Software, and to
	permit persons to whom the Software is furnished to do so, subject to
	the following conditions:

	The above copyright notice and this permission notice shall be
	included in all copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
	EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
	MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
	NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
	LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
	OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
	WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

*/


#ifndef IO_TYPES
#define IO_TYPES
#define   __R     volatile const unsigned int
#define   __W     volatile       unsigned int
#define   __RW    volatile       unsigned int
#endif

#define SW_AES_STATUS_REG_READY_REG		7
#define SW_AES_STATUS_REG_READY_REG_LEN	1
#define SW_AES_STATUS_REG_VALID_REG		8
#define SW_AES_STATUS_REG_VALID_REG_LEN	1
#define SW_AES_CTRL_REG_INIT_REG		0
#define SW_AES_CTRL_REG_INIT_REG_LEN	1
#define SW_AES_CTRL_REG_NEXT_REG		1
#define SW_AES_CTRL_REG_NEXT_REG_LEN	1
#define SW_AES_CTRL_REG_ENCDEC_REG		2
#define SW_AES_CTRL_REG_ENCDEC_REG_LEN	1
#define SW_AES_CTRL_REG_KEYLEN_REG		3
#define SW_AES_CTRL_REG_KEYLEN_REG_LEN	1
#define SW_AES_VALID_FLAG	0x1
#define SW_AES_READY_FLAG	0x2

typedef struct _SW_AES_TYPE_ {
	__R 	STATUS;
	__RW	CTRL;
	__RW	KEY0;
	__RW	KEY1;
	__RW	KEY2;
	__RW	KEY3;
	__RW	KEY4;
	__RW	KEY5;
	__RW	KEY6;
	__RW	KEY7;
	__RW	BLOCK0;
	__RW	BLOCK1;
	__RW	BLOCK2;
	__RW	BLOCK3;
	__R 	RESULT0;
	__R 	RESULT1;
	__R 	RESULT2;
	__R 	RESULT3;
	__R 	reserved[942];
	__W 	icr;
	__R 	ris;
	__RW	im;
	__R 	mis;
} SW_AES_TYPE;
